version: '3'
services:
    api-nginx:
        build:
            context: ./api/docker
            dockerfile: nginx.docker
        volumes:
            -  ./api:/var/www/api
        depends_on:
            - api-php-fpm
        ports:
            - "8080:80"

    api-php-fpm:
        build:
            context: ./api/docker
            dockerfile: php-fpm.docker
        volumes:
            - ./api:/var/www/api
        depends_on:
            - api-postgres

    api-php-cli:
        build:
            context: ./api/docker
            dockerfile: php-cli.docker
        volumes:
            - ./api:/var/www/api
        depends_on:
            - api-postgres
        working_dir: /var/www/api
        tty: true 

    api-postgres:
        image: postgres:11.2-alpine
        volumes:
            - ./api/var/docker/postgres:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=app"
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=api"
        ports:
            - "54321:5432"
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - api-postgres
        ports:
          - "8081:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped
