version: "3"
services:
    nginx:
        image: nginx:1.10
        restart: always
        volumes:
            - ./api:/var/www/api
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - frontend
            - backend
        ports:
            - "81:80"
        labels:
            - "traefik.backend=nginx"
            - "traefik.frontend.rule=Host:${DOMAIN}"
            - "traefik.docker.network=frontend"
            - "traefik.port=80"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"

    php:
        image: hub.t-me.pp.ua/romaxa/baza-api:latest
        command: bash -c "chmod +x ./init.sh && sh ./init.sh && php-fpm"
        volumes:
            - ./api:/var/www/api
            - ./init.sh:/var/www/init.sh
        depends_on:
            - api-postgres
        networks:
            - backend
        labels:
            - "traefik.enable=false"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"

    api-postgres:
        image: postgres:11.2-alpine
        volumes:
            - ./api/var/docker/postgres:/var/lib/postgresql/data
        environment:
            - "POSTGRES_USER=app"
            - "POSTGRES_PASSWORD=secret"
            - "POSTGRES_DB=api"
        networks:
            - backend
        labels:
            - "traefik.enable=false"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"

    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - api-postgres
        networks:
            - frontend
            - backend
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped
        labels:
            - "traefik.backend=pgadmin"
            - "traefik.frontend.rule=Host:pgadmin.${DOMAIN}"
            - "traefik.docker.network=frontend"
            - "traefik.port=80"
        logging:
            driver: "json-file"
            options:
                max-size: "50m"
                max-file: "3"

networks:
    frontend:
        external: true
    backend:
        external: false
